version = 0.1
[default]
[default.global]
[default.global.parameters]
stack_name = "ygpp"
region = "us-east-1"

[default.deploy.parameters]
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = true
resolve_s3 = true

parameter_overrides = "AllowedOrigin=\"https://math-s.github.io\""
s3_prefix = "ygpp"
image_repositories = []
